106 protect cook and admin pages
GSG-G13/MenuMingle pull request #109
Opened 2023-07-09 20:06 UTC by momenmarwan

2023-07-09 20:10 UTC, Farah202324 approved these changes

2023-07-10 09:26 UTC, momenqudaih requested changes

2023-07-10 09:26 UTC, momenqudaih commented on client/src/pages/Login.tsx
> +  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
**handleSubmit not working when submit the sign in form**

2023-07-10 09:51 UTC, momenqudaih approved these changes

2023-07-10 10:29 UTC, merged