README and img files
GSG-G13/MenuMingle pull request #17
Opened 2023-06-12 12:11 UTC by Farah202324

README and img files

2023-06-12 18:14 UTC, momenqudaih approved these changes

2023-06-12 18:21 UTC, momenmarwan submitted a review, later dismissed

2023-06-12 18:32 UTC, moustf commented on README.md
> +# Features
Name the features as User Stories, and each story needs to start with `As a user, I should be able to ...`.

E.g.: As a restaurant owner user, I should be able to register and authenticate my staff.

2023-06-12 18:34 UTC, moustf commented on README.md
> +# User Story
This should e the user journey.

User journey illustrated the journey of our client on the website.
E.x.: When the user goes to a restaurant to eat, the user will find a QR taped to each table, after scanning this QR, our website will be opened and the user can order from the menu, (and you complete this way).

2023-06-12 18:36 UTC, moustf requested changes
Really pretty shaping, just added a few notes.
Thank you, Farah!

2023-06-12 18:44 UTC, momenqudaih commented on README.md
> +#### team:
add mentions like that @Farah202324  plz

2023-06-12 21:01 UTC, momenqudaih approved these changes
Good job farah 😍💪

2023-06-13 02:22 UTC, momenmarwan approved these changes

2023-06-13 07:27 UTC, closed without merging