feat: added the first part of the file structure
GSG-G13/MenuMingle pull request #2
Opened 2023-06-08 08:29 UTC by moustf

- Creating the file structure.
- **This PR is still in progress**.

2023-06-08 16:42 UTC, momenmarwan approved these changes

2023-06-08 20:52 UTC, momenmarwan requested changes

2023-06-08 20:52 UTC, momenmarwan commented on .eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
why you turn off the any of typescript what the point of typescript

2023-06-08 20:52 UTC, momenmarwan commented on server/index.ts
> +app.listen(port, () => {
this function doesn't return anything why we don't use the void keyword

2023-06-08 20:52 UTC, momenmarwan commented on server/app.ts
> +export const app = express();
we should specify the type of app maybe we use 
 const app: Application = express();
or 
const app: Express = express();
I don't know what is better

2023-06-09 11:46 UTC, Farah202324 commented on client/src/App.tsx
import './App.css';

function App(): React.ReactElement {
  return <div>hello</div>;

}

export default App;

By adding : React.ReactElement after the function name, you explicitly state that the App function returns a ReactElement. This helps TypeScript analyze and enforce type correctness in your code.

2023-06-09 12:41 UTC, Farah202324 commented on .eslintrc.js
any is not suppose to be allowed

2023-06-11 09:21 UTC, closed without merging