perf: add the server error client error custome error
GSG-G13/MenuMingle pull request #20
Opened 2023-06-12 13:50 UTC by momenmarwan

add server error and client error custom error middleware

2023-06-12 18:15 UTC, Farah202324 approved these changes

2023-06-12 18:24 UTC, momenqudaih submitted a review, later dismissed

2023-06-13 02:20 UTC, moustf commented on server/middleware/clientError.ts
> +import { Request, Response } from 'express';
Add a new line between the imports and the function.

2023-06-13 02:20 UTC, moustf commented on server/middleware/clientError.ts
> +    massage: 'page not found',
Edit the typo; message.

2023-06-13 02:21 UTC, moustf commented on server/middleware/serverError.ts
> +      status: 401,
Wrong data response is 400, and you don't have to include it in the response.

2023-06-13 02:35 UTC, moustf commented on server/middleware/serverError.ts
> +  if (err instanceof ValidationError) {
When you throw a new CustomError each time you face an error in your controller, you don't need these checks.
You have to decide on a paradigm to use with your team.

2023-06-13 02:36 UTC, moustf commented on server/utils/helper/customError.ts
> +    super(msg);
add
```ts
this.status = status;
```

2023-06-13 02:37 UTC, moustf requested changes
Please refer to my last message on the Discord channel for further details.

2023-06-13 08:58 UTC, Farah202324 submitted a review, later dismissed

2023-06-13 09:12 UTC, Farah202324 approved these changes

2023-06-13 09:22 UTC, momenqudaih approved these changes

2023-06-13 09:24 UTC, moustf approved these changes

2023-06-13 09:25 UTC, merged