feat: add the login controller
GSG-G13/MenuMingle pull request #40
Opened 2023-06-17 16:39 UTC by momenmarwan

Title: Implement Pull Request Route

Description:
We need to implement a pull request route to enable users to propose changes to our codebase. This route will handle the creation and management of pull requests.

Route Details:

Method: POST
Full Route: /api/v1/login

Request Body:

The route should expect the following fields in the request body:
Request Body:

The route should expect the following fields in the request body:

username (string, required): The email address of the user.
password (string, required): The password for the user's account.
Response:

The route should respond with a JSON object containing the following fields:

success (boolean): Indicates whether the login was successful.
message (string): A message providing feedback on the login process.
token (string): A JSON Web Token (JWT) to be used for authentication in subsequent requests.
Please implement the above requirements for the login route.

2023-06-17 19:43 UTC, moustf commented on server/__test__/singup.test.ts
> +        expect(res.body.msg).toBe('the user has been created successfully');
The message in the response body is not the same as this message in the test, so it's failing.
Change the message to make it pass.

---
![Screenshot from 2023-06-17 22-40-52](https://github.com/GSG-G13/MenuMingle/assets/77394697/82cf3313-3417-42eb-84c2-edd28b5af9cf)

2023-06-17 20:02 UTC, moustf requested changes

2023-06-17 20:02 UTC, moustf commented on server/__test__/login.test.ts
> +  // it('Testing the success path, the controller should return 201 stats code.', done => {
The login should be in the same test as illustrated above.

2023-06-18 08:08 UTC, Farah202324 submitted a review, later dismissed

2023-06-18 11:30 UTC, Farah202324 submitted a review, later dismissed

2023-06-18 12:47 UTC, momenqudaih requested changes
Sign token when user logged successfully.

2023-06-18 13:07 UTC, Farah202324 approved these changes

2023-06-18 13:11 UTC, momenqudaih approved these changes

2023-06-18 13:19 UTC, moustf approved these changes

2023-06-18 13:25 UTC, merged